//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OkulSabahDBEntities : DbContext
    {
        public OkulSabahDBEntities()
            : base("name=OkulSabahDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<Branslar> Branslar { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<IdariKadro> IdariKadro { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<KanGruplari> KanGruplari { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Kulupler> Kulupler { get; set; }
        public virtual DbSet<Notlar> Notlar { get; set; }
        public virtual DbSet<OgrenciDers> OgrenciDers { get; set; }
        public virtual DbSet<OgrenciIzin> OgrenciIzin { get; set; }
        public virtual DbSet<Ogrenciler> Ogrenciler { get; set; }
        public virtual DbSet<OgrenciProje> OgrenciProje { get; set; }
        public virtual DbSet<OgrenciTakim> OgrenciTakim { get; set; }
        public virtual DbSet<OgrenciVeli> OgrenciVeli { get; set; }
        public virtual DbSet<OgretmenBilgileri> OgretmenBilgileri { get; set; }
        public virtual DbSet<OgretmenDers> OgretmenDers { get; set; }
        public virtual DbSet<OgretmenIzin> OgretmenIzin { get; set; }
        public virtual DbSet<Ogretmenler> Ogretmenler { get; set; }
        public virtual DbSet<OgretmenProje> OgretmenProje { get; set; }
        public virtual DbSet<OkulTakimi> OkulTakimi { get; set; }
        public virtual DbSet<PersonelBilgileri> PersonelBilgileri { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<Projeler> Projeler { get; set; }
        public virtual DbSet<Sınıflar> Sınıflar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TakimOgretmenleri> TakimOgretmenleri { get; set; }
        public virtual DbSet<Veliler> Veliler { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
        public virtual DbSet<Yoklama> Yoklama { get; set; }
        public virtual DbSet<vw_OgrenciBilgileri> vw_OgrenciBilgileri { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_DersAlanOgrenci_Result> sp_DersAlanOgrenci(string dersAdi)
        {
            var dersAdiParameter = dersAdi != null ?
                new ObjectParameter("DersAdi", dersAdi) :
                new ObjectParameter("DersAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DersAlanOgrenci_Result>("sp_DersAlanOgrenci", dersAdiParameter);
        }
    
        public virtual ObjectResult<sp_DersAlanOgrenciler_Result> sp_DersAlanOgrenciler(string dersAdi)
        {
            var dersAdiParameter = dersAdi != null ?
                new ObjectParameter("DersAdi", dersAdi) :
                new ObjectParameter("DersAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DersAlanOgrenciler_Result>("sp_DersAlanOgrenciler", dersAdiParameter);
        }
    
        public virtual int sp_DersEkle(string dersAdi)
        {
            var dersAdiParameter = dersAdi != null ?
                new ObjectParameter("DersAdi", dersAdi) :
                new ObjectParameter("DersAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DersEkle", dersAdiParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_IdariKadroGuncelle(Nullable<int> idariKadroID, string unvanAdı, Nullable<int> ogretmenID, string dipNo)
        {
            var idariKadroIDParameter = idariKadroID.HasValue ?
                new ObjectParameter("IdariKadroID", idariKadroID) :
                new ObjectParameter("IdariKadroID", typeof(int));
    
            var unvanAdıParameter = unvanAdı != null ?
                new ObjectParameter("unvanAdı", unvanAdı) :
                new ObjectParameter("unvanAdı", typeof(string));
    
            var ogretmenIDParameter = ogretmenID.HasValue ?
                new ObjectParameter("OgretmenID", ogretmenID) :
                new ObjectParameter("OgretmenID", typeof(int));
    
            var dipNoParameter = dipNo != null ?
                new ObjectParameter("DipNo", dipNo) :
                new ObjectParameter("DipNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_IdariKadroGuncelle", idariKadroIDParameter, unvanAdıParameter, ogretmenIDParameter, dipNoParameter);
        }
    
        public virtual int sp_IdariKadroGuncelle1(Nullable<int> idariKadroID, string unvanAdi, Nullable<int> ogretmenID, string dipNo, string yetki)
        {
            var idariKadroIDParameter = idariKadroID.HasValue ?
                new ObjectParameter("IdariKadroID", idariKadroID) :
                new ObjectParameter("IdariKadroID", typeof(int));
    
            var unvanAdiParameter = unvanAdi != null ?
                new ObjectParameter("UnvanAdi", unvanAdi) :
                new ObjectParameter("UnvanAdi", typeof(string));
    
            var ogretmenIDParameter = ogretmenID.HasValue ?
                new ObjectParameter("OgretmenID", ogretmenID) :
                new ObjectParameter("OgretmenID", typeof(int));
    
            var dipNoParameter = dipNo != null ?
                new ObjectParameter("DipNo", dipNo) :
                new ObjectParameter("DipNo", typeof(string));
    
            var yetkiParameter = yetki != null ?
                new ObjectParameter("yetki", yetki) :
                new ObjectParameter("yetki", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_IdariKadroGuncelle1", idariKadroIDParameter, unvanAdiParameter, ogretmenIDParameter, dipNoParameter, yetkiParameter);
        }
    
        public virtual int sp_IdariKadroGuncelle2(Nullable<int> idariKadroID, string unvanAdi, Nullable<int> ogretmenID, string dipNo, string yetki)
        {
            var idariKadroIDParameter = idariKadroID.HasValue ?
                new ObjectParameter("IdariKadroID", idariKadroID) :
                new ObjectParameter("IdariKadroID", typeof(int));
    
            var unvanAdiParameter = unvanAdi != null ?
                new ObjectParameter("UnvanAdi", unvanAdi) :
                new ObjectParameter("UnvanAdi", typeof(string));
    
            var ogretmenIDParameter = ogretmenID.HasValue ?
                new ObjectParameter("OgretmenID", ogretmenID) :
                new ObjectParameter("OgretmenID", typeof(int));
    
            var dipNoParameter = dipNo != null ?
                new ObjectParameter("DipNo", dipNo) :
                new ObjectParameter("DipNo", typeof(string));
    
            var yetkiParameter = yetki != null ?
                new ObjectParameter("yetki", yetki) :
                new ObjectParameter("yetki", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_IdariKadroGuncelle2", idariKadroIDParameter, unvanAdiParameter, ogretmenIDParameter, dipNoParameter, yetkiParameter);
        }
    
        public virtual ObjectResult<sp_Ogrenciler_Result> sp_Ogrenciler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Ogrenciler_Result>("sp_Ogrenciler");
        }
    
        public virtual ObjectResult<sp_OgrencilerinSiniflari_Result> sp_OgrencilerinSiniflari()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OgrencilerinSiniflari_Result>("sp_OgrencilerinSiniflari");
        }
    
        public virtual ObjectResult<sp_ogrencisiniflari_Result> sp_ogrencisiniflari()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ogrencisiniflari_Result>("sp_ogrencisiniflari");
        }
    
        public virtual int sp_PersonelGiriCikisBilgileri(string tC)
        {
            var tCParameter = tC != null ?
                new ObjectParameter("TC", tC) :
                new ObjectParameter("TC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PersonelGiriCikisBilgileri", tCParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_SinifEkle(string sinifNo, string sinifSubesi, Nullable<int> ogretmenID, Nullable<int> bolumID)
        {
            var sinifNoParameter = sinifNo != null ?
                new ObjectParameter("SinifNo", sinifNo) :
                new ObjectParameter("SinifNo", typeof(string));
    
            var sinifSubesiParameter = sinifSubesi != null ?
                new ObjectParameter("SinifSubesi", sinifSubesi) :
                new ObjectParameter("SinifSubesi", typeof(string));
    
            var ogretmenIDParameter = ogretmenID.HasValue ?
                new ObjectParameter("OgretmenID", ogretmenID) :
                new ObjectParameter("OgretmenID", typeof(int));
    
            var bolumIDParameter = bolumID.HasValue ?
                new ObjectParameter("BolumID", bolumID) :
                new ObjectParameter("BolumID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SinifEkle", sinifNoParameter, sinifSubesiParameter, ogretmenIDParameter, bolumIDParameter);
        }
    
        public virtual int sp_SinifGuncelle(Nullable<int> siniflarID, string sinifNo, string sinifSubesi, Nullable<int> ogretmenID, Nullable<int> bolumID, string yetki)
        {
            var siniflarIDParameter = siniflarID.HasValue ?
                new ObjectParameter("SiniflarID", siniflarID) :
                new ObjectParameter("SiniflarID", typeof(int));
    
            var sinifNoParameter = sinifNo != null ?
                new ObjectParameter("SinifNo", sinifNo) :
                new ObjectParameter("SinifNo", typeof(string));
    
            var sinifSubesiParameter = sinifSubesi != null ?
                new ObjectParameter("SinifSubesi", sinifSubesi) :
                new ObjectParameter("SinifSubesi", typeof(string));
    
            var ogretmenIDParameter = ogretmenID.HasValue ?
                new ObjectParameter("OgretmenID", ogretmenID) :
                new ObjectParameter("OgretmenID", typeof(int));
    
            var bolumIDParameter = bolumID.HasValue ?
                new ObjectParameter("BolumID", bolumID) :
                new ObjectParameter("BolumID", typeof(int));
    
            var yetkiParameter = yetki != null ?
                new ObjectParameter("yetki", yetki) :
                new ObjectParameter("yetki", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SinifGuncelle", siniflarIDParameter, sinifNoParameter, sinifSubesiParameter, ogretmenIDParameter, bolumIDParameter, yetkiParameter);
        }
    
        public virtual int sp_SinifGuncelle1(Nullable<int> siniflarID, string sinifNo, string sinifSubesi, Nullable<int> ogretmenID, Nullable<int> bolumID, string yetki)
        {
            var siniflarIDParameter = siniflarID.HasValue ?
                new ObjectParameter("SiniflarID", siniflarID) :
                new ObjectParameter("SiniflarID", typeof(int));
    
            var sinifNoParameter = sinifNo != null ?
                new ObjectParameter("SinifNo", sinifNo) :
                new ObjectParameter("SinifNo", typeof(string));
    
            var sinifSubesiParameter = sinifSubesi != null ?
                new ObjectParameter("SinifSubesi", sinifSubesi) :
                new ObjectParameter("SinifSubesi", typeof(string));
    
            var ogretmenIDParameter = ogretmenID.HasValue ?
                new ObjectParameter("OgretmenID", ogretmenID) :
                new ObjectParameter("OgretmenID", typeof(int));
    
            var bolumIDParameter = bolumID.HasValue ?
                new ObjectParameter("BolumID", bolumID) :
                new ObjectParameter("BolumID", typeof(int));
    
            var yetkiParameter = yetki != null ?
                new ObjectParameter("yetki", yetki) :
                new ObjectParameter("yetki", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SinifGuncelle1", siniflarIDParameter, sinifNoParameter, sinifSubesiParameter, ogretmenIDParameter, bolumIDParameter, yetkiParameter);
        }
    
        public virtual int sp_SinifSilme(Nullable<int> siniflarD, string yetkiAdi)
        {
            var siniflarDParameter = siniflarD.HasValue ?
                new ObjectParameter("SiniflarD", siniflarD) :
                new ObjectParameter("SiniflarD", typeof(int));
    
            var yetkiAdiParameter = yetkiAdi != null ?
                new ObjectParameter("yetkiAdi", yetkiAdi) :
                new ObjectParameter("yetkiAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SinifSilme", siniflarDParameter, yetkiAdiParameter);
        }
    
        public virtual int sp_SinifSilme1(Nullable<int> siniflarID, string yetki)
        {
            var siniflarIDParameter = siniflarID.HasValue ?
                new ObjectParameter("SiniflarID", siniflarID) :
                new ObjectParameter("SiniflarID", typeof(int));
    
            var yetkiParameter = yetki != null ?
                new ObjectParameter("yetki", yetki) :
                new ObjectParameter("yetki", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SinifSilme1", siniflarIDParameter, yetkiParameter);
        }
    
        public virtual ObjectResult<sp_SubeyegoreListeler_Result> sp_SubeyegoreListeler(string subeAdi)
        {
            var subeAdiParameter = subeAdi != null ?
                new ObjectParameter("subeAdi", subeAdi) :
                new ObjectParameter("subeAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SubeyegoreListeler_Result>("sp_SubeyegoreListeler", subeAdiParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_VeliEkle(string tc, string adi, string soyad, string cinsiyet, Nullable<System.DateTime> dogumTarihi, Nullable<int> dogumYeriID, string telefon, string adres, string medeniHali, Nullable<int> kanGrubuID, Nullable<int> kulID)
        {
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var adiParameter = adi != null ?
                new ObjectParameter("adi", adi) :
                new ObjectParameter("adi", typeof(string));
    
            var soyadParameter = soyad != null ?
                new ObjectParameter("soyad", soyad) :
                new ObjectParameter("soyad", typeof(string));
    
            var cinsiyetParameter = cinsiyet != null ?
                new ObjectParameter("cinsiyet", cinsiyet) :
                new ObjectParameter("cinsiyet", typeof(string));
    
            var dogumTarihiParameter = dogumTarihi.HasValue ?
                new ObjectParameter("DogumTarihi", dogumTarihi) :
                new ObjectParameter("DogumTarihi", typeof(System.DateTime));
    
            var dogumYeriIDParameter = dogumYeriID.HasValue ?
                new ObjectParameter("DogumYeriID", dogumYeriID) :
                new ObjectParameter("DogumYeriID", typeof(int));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            var medeniHaliParameter = medeniHali != null ?
                new ObjectParameter("MedeniHali", medeniHali) :
                new ObjectParameter("MedeniHali", typeof(string));
    
            var kanGrubuIDParameter = kanGrubuID.HasValue ?
                new ObjectParameter("KanGrubuID", kanGrubuID) :
                new ObjectParameter("KanGrubuID", typeof(int));
    
            var kulIDParameter = kulID.HasValue ?
                new ObjectParameter("kulID", kulID) :
                new ObjectParameter("kulID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_VeliEkle", tcParameter, adiParameter, soyadParameter, cinsiyetParameter, dogumTarihiParameter, dogumYeriIDParameter, telefonParameter, adresParameter, medeniHaliParameter, kanGrubuIDParameter, kulIDParameter);
        }
    
        public virtual int sp_VeliEkle1(string tC, string ad, string soyad, string cinsiyet, Nullable<System.DateTime> dTarihi, Nullable<int> dYeriID, string tel, string adres, string medeniHali, Nullable<int> kanGrubuID, Nullable<int> kulID)
        {
            var tCParameter = tC != null ?
                new ObjectParameter("TC", tC) :
                new ObjectParameter("TC", typeof(string));
    
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var soyadParameter = soyad != null ?
                new ObjectParameter("Soyad", soyad) :
                new ObjectParameter("Soyad", typeof(string));
    
            var cinsiyetParameter = cinsiyet != null ?
                new ObjectParameter("Cinsiyet", cinsiyet) :
                new ObjectParameter("Cinsiyet", typeof(string));
    
            var dTarihiParameter = dTarihi.HasValue ?
                new ObjectParameter("DTarihi", dTarihi) :
                new ObjectParameter("DTarihi", typeof(System.DateTime));
    
            var dYeriIDParameter = dYeriID.HasValue ?
                new ObjectParameter("DYeriID", dYeriID) :
                new ObjectParameter("DYeriID", typeof(int));
    
            var telParameter = tel != null ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var medeniHaliParameter = medeniHali != null ?
                new ObjectParameter("MedeniHali", medeniHali) :
                new ObjectParameter("MedeniHali", typeof(string));
    
            var kanGrubuIDParameter = kanGrubuID.HasValue ?
                new ObjectParameter("KanGrubuID", kanGrubuID) :
                new ObjectParameter("KanGrubuID", typeof(int));
    
            var kulIDParameter = kulID.HasValue ?
                new ObjectParameter("KulID", kulID) :
                new ObjectParameter("KulID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_VeliEkle1", tCParameter, adParameter, soyadParameter, cinsiyetParameter, dTarihiParameter, dYeriIDParameter, telParameter, adresParameter, medeniHaliParameter, kanGrubuIDParameter, kulIDParameter);
        }
    
        public virtual int sp_YetkiSil(Nullable<int> iD, string yetkiAdi)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var yetkiAdiParameter = yetkiAdi != null ?
                new ObjectParameter("yetkiAdi", yetkiAdi) :
                new ObjectParameter("yetkiAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_YetkiSil", iDParameter, yetkiAdiParameter);
        }
    
        public virtual int sp_YetkiSil1(Nullable<int> yetkilerID, string yetki)
        {
            var yetkilerIDParameter = yetkilerID.HasValue ?
                new ObjectParameter("YetkilerID", yetkilerID) :
                new ObjectParameter("YetkilerID", typeof(int));
    
            var yetkiParameter = yetki != null ?
                new ObjectParameter("Yetki", yetki) :
                new ObjectParameter("Yetki", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_YetkiSil1", yetkilerIDParameter, yetkiParameter);
        }
    }
}
