//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotlarID { get; set; }
        public string HarfDegeri { get; set; }
        public string SayısalDegeri { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<System.DateTime> Sınav1Tarih { get; set; }
        public Nullable<decimal> Sınav1 { get; set; }
        public Nullable<System.DateTime> Sınav2Tarih { get; set; }
        public Nullable<decimal> Sınav2 { get; set; }
        public Nullable<System.DateTime> Odev1Tarih { get; set; }
        public Nullable<decimal> Odev1 { get; set; }
        public Nullable<System.DateTime> Odev2Tarih { get; set; }
        public Nullable<decimal> Odev2 { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<decimal> Kanaat1 { get; set; }
        public Nullable<System.DateTime> KanaatTarihi1 { get; set; }
        public Nullable<decimal> Kanaat2 { get; set; }
        public Nullable<System.DateTime> KanaatTarihi2 { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
