//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogretmenler()
        {
            this.IdariKadro = new HashSet<IdariKadro>();
            this.OgretmenBilgileri = new HashSet<OgretmenBilgileri>();
            this.OgretmenDers = new HashSet<OgretmenDers>();
            this.OgretmenIzin = new HashSet<OgretmenIzin>();
            this.OgretmenProje = new HashSet<OgretmenProje>();
            this.Sınıflar = new HashSet<Sınıflar>();
            this.TakimOgretmenleri = new HashSet<TakimOgretmenleri>();
        }
    
        public int OgretmenlerID { get; set; }
        public string OgretmenTC { get; set; }
        public string OgretmenAdi { get; set; }
        public string OgretmenSoyadi { get; set; }
        public string Cinsiyet { get; set; }
        public string Telefon { get; set; }
        public string MedeniHali { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DogumYeriID { get; set; }
        public string Adres { get; set; }
        public Nullable<int> KanGrubuID { get; set; }
        public Nullable<int> BransID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Branslar Branslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdariKadro> IdariKadro { get; set; }
        public virtual iller iller { get; set; }
        public virtual KanGruplari KanGruplari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgretmenBilgileri> OgretmenBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgretmenDers> OgretmenDers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgretmenIzin> OgretmenIzin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgretmenProje> OgretmenProje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sınıflar> Sınıflar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakimOgretmenleri> TakimOgretmenleri { get; set; }
    }
}
