//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Notlar = new HashSet<Notlar>();
            this.OgrenciDers = new HashSet<OgrenciDers>();
            this.OgrenciProje = new HashSet<OgrenciProje>();
            this.OgrenciTakim = new HashSet<OgrenciTakim>();
            this.OgrenciVeli = new HashSet<OgrenciVeli>();
            this.Yoklama = new HashSet<Yoklama>();
        }
    
        public int OgrencilerID { get; set; }
        public string OgrenciTC { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public string Cinsiyeti { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DogumYeriID { get; set; }
        public string Adres { get; set; }
        public Nullable<decimal> OgrenciKilo { get; set; }
        public Nullable<decimal> OgrenciBoy { get; set; }
        public Nullable<int> KanGrubuID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> SinifID { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual KanGruplari KanGruplari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
        public virtual Sınıflar Sınıflar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciProje> OgrenciProje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciTakim> OgrenciTakim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciVeli> OgrenciVeli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yoklama> Yoklama { get; set; }
    }
}
