//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelBilgileri
    {
        public int PersonelBilgileriID { get; set; }
        public int PersonelID { get; set; }
        public System.DateTime GirisTarih { get; set; }
        public Nullable<System.DateTime> CikisTarih { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
