//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veliler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veliler()
        {
            this.OgrenciVeli = new HashSet<OgrenciVeli>();
        }
    
        public int VelilerID { get; set; }
        public string VeliTC { get; set; }
        public string VeliAdi { get; set; }
        public string VeliSoyadi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DogumYeriID { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string MedeniHali { get; set; }
        public Nullable<int> KanGrubuID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual KanGruplari KanGruplari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciVeli> OgrenciVeli { get; set; }
    }
}
