//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OgrenciBilgileri
    {
        public int OgrencilerID { get; set; }
        public string OgrenciTC { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public string Cinsiyeti { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Adres { get; set; }
        public string Sınıf { get; set; }
        public string KanGrubuAdi { get; set; }
        public string DogumYeri { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
