//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190421_1_OOP_Ornek_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yoklama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yoklama()
        {
            this.OgrenciIzin = new HashSet<OgrenciIzin>();
        }
    
        public int YoklamalarID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<System.DateTime> YoklamaTarih { get; set; }
        public string Devamsızlık { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciIzin> OgrenciIzin { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
